from app.models import db, City, environment, SCHEMA
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_cities():

    grand_junction = City(city='Grand Junction')
    carbondale = City(city='Carbondale')
    loma = City(city='Loma')
    rifle = City(city='Rifle')
    montrose = City(city='Montrose')
    silt = City(city='Silt')
    nucla = City(city='Nucla')
    union_grove = City(city='Union Grove')
    delta = City(city='Delta')
    silverthorne = City(city='Silverthorne')
    lincoln = City(city='Lincoln')
    new_castle = City(city='New Castle')
    craig = City(city='Craig')
    commerce_city = City(city='Commerce City')
    centennial = City(city='Centennial')
    spokane = City(city='Spokane')
    clifton = City(city='Clifton')
    denver = City(city='Denver')
    hotchkiss = City(city='Hotchkiss')
    olathe = City(city='Olathe')
    steamboat_springs = City(city='Steamboat Springs')
    glenwood_springs = City(city='Glenwood Springs')
    telluride = City(city='Telluride')
    golden = City(city='Golden')
    thorton = City(city='Thorton')
    panama_city = City(city='Panama City')
    fruita = City(city='Fruita')
    gladstone = City(city='Gladstone')
    vernal = City(city='Vernal')
    gunnison = City(city='Gunnison')
    ridgway = City(city='Ridgway')
    pueblo_west = City(city='Pueblo West')
    windsor = City(city='Windsor')
    kalama = City(city='Kalama')
    empire = City(city='Empire')
    highlands_ranch = City(city='Highlands Ranch')
    aurora = City(city='Aurora')
    paonia = City(city='Paonia')
    aspen = City(city='Aspen')
    mesa = City(city='Mesa')
    myron = City(city='Myron')
    buffdale = City(city='Buffdale')
    parachute = City(city='Parachute')
    frisco = City(city='Frisco')
    kremmling = City(city='Kremmling')
    breckenridge = City(city='Breckenridge')
    palisade = City(city='Palisade')
    parker = City(city='Parker')
    colorado_springs = City(city='Colorado Springs')
    hayden = City(city='Hayden')
    basalt = City(city='Basalt')
    idaho_springs = City(city='Idaho Springs')
    farmington = City(city='Farmington')
    roosevelt = City(city='Roosevelt')
    frederick = City(city='Frederick')
    norwood = City(city='Norwood')
    ft_lupton = City(city='Ft. Lupton')
    fort_collins = City(city='Fort Collins')
    st_augustine = City(city='St. Augustine')
    eagle = City(city='Eagle')
    loveland = City(city='Loveland')
    englewood = City(city='Englewood')
    durango = City(city='Durango')
    santa_ana = City(city='Santa Ana')
    gypsum = City(city='Gypsum')
    longmont = City(city='Longmont')
    phoenix = City(city='Phoenix')
    brighton = City(city='Brighton')
    dacono = City(city='Dacono')
    ouray = City(city='Ouray')
    los_angelas = City(city='Los Angelas')
    wolcott = City(city='Wolcott')
    arvada = City(city='Arvada')
    littleton = City(city='Littleton')
    dove_creek = City(city='Dove Creek')
    lindon = City(city='Lindon')
    scottsbluff = City(city='Scottsbluff')
    oklahoma_city = City(city='Oklahoma City')
    wood_dale = City(city='Wood Dale')
    columbus = City(city='Columbus')
    herber_city = City(city='Herber City')
    grand_island = City(city='Grand Island')
    austin = City(city='Austin')
    cumming = City(city='Cumming')
    johnstown = City(city='Johnstown')
    san_diego = City(city='San Diego')
    stafford = City(city='Stafford')
    bogart = City(city='Bogart')
    de_beque = City(city='De Beque')
    modesto = City(city='Modesto')
    lehi = City(city='Lehi')
    champlain = City(city='Champlain')
    delray_beach = City(city='Delray Beach')
    san_fransico = City(city='San Francisco')
    draper = City(city='Draper')
    wheat_ridge = City(city='Wheat Ridge')
    yoder = City(city='Yoder')
    cheyenne = City(city='Cheyenne')
    caldwell = City(city='Caldwell')
    moroni = City(city='Moroni')
    cave_creek = City(city='Cave Creek')
    salt_lake_city = City(city='Salt Lake City')
    tarzana = City(city='Tarzana')
    denton = City(city='Denton')
    castle_rock = City(city='Castle Rock')
    fargo = City(city='Fargo')
    kansas_city = City(city='Kansas City')
    hildale = City(city='Hildale')
    collbran = City(city='Collbran')
    lakewood = City(city='Lakewood')
    avon = City(city='Avon')
    pueblo = City(city='Pueblo')
    garland = City(city='Garland')
    greenwood_village = City(city='Greenwood Village')
    albuquerque = City(city='Albuquerque')
    marietta = City(city='Marietta')
    morrison = City(city='Morrison')
    belgrade = City(city='Belgrade')
    crawford = City(city='Crawford')
    troy = City(city='Troy')
    sandy = City(city='Sandy')
    greeley = City(city='Greeley')
    broomfield = City(city='Broomfield')
    carson = City(city='Carson')
    houston = City(city='Houston')
    cortez = City(city='Cortez')
    whitewater = City(city='Whitewater')
    greenville = City(city='Greenville')
    mchenry = City(city='McHenry')
    madison = City(city='Madison')
    flagstaff = City(city='Flagstaff')
    portsmouth = City(city='Portsmouth')
    midway = City(city='Midway')
    hoboken = City(city='Hoboken')
    cincinnati = City(city='Cincinnati')
    monument = City(city='Monument')
    little_canada = City(city='Little Canada')
    grand_rapids = City(city='Grand Rapids')
    cedaredge = City(city='Cedaredge')
    glade_park = City(city='Glade Park')
    granby = City(city='Granby')
    gentry = City(city='Gentry')
    provo = City(city='Provo')
    casa_grande = City(city='Casa Grande')
    west_jordan = City(city='West Jordan')
    gaithersburg = City(city='Gaithersburg')
    carrollton = City(city='Carrollton')
    farmers_branch = City(city='Farmer\'s Branch')
    milwaukee = City(city='Milwaukee')
    centerville = City(city='Centerville')
    lake_elmo = City(city='Lake Elmo')
    dallas = City(city='Dallas')
    muskego = City(city='Muskego')
    janesville = City(city='Janesville')
    cleveland = City(city='Cleveland')
    venus = City(city='Venus')
    cerritos = City(city='Cerritos')
    e_setauket = City(city='E. Setauket')
    westfield = City(city='Westfield')
    downey = City(city='Downey')
    medina = City(city='Medina')
    san_antonio = City(city='San Antonio')
    west_warwick = City(city='West Warwick')
    conway = City(city='Conway')
    kent = City(city='Kent')
    thousand_palms = City(city='Thousand Palms')
    walton_hills = City(city='Walton Hills')
    londonerry = City(city='Londonerry')
    crown_point = City(city='Crown Point')
    tulsa = City(city='Tulsa')
    snowmass = City(city='Snowmass')
    rangley = City(city='Rangley')
    ripon = City(city='Ripon')
    trinidad = City(city='Trinidad')
    phippsburg = City(city='Phippsburg')
    crested_butte = City(city='Crested Butte')
    leadville = City(city='Leadville')

    list = [grand_junction, carbondale, loma, rifle, montrose, silt, nucla, union_grove, delta, silverthorne, lincoln, new_castle, craig, commerce_city, centennial, spokane, clifton, denver, hotchkiss, olathe, steamboat_springs, glenwood_springs, telluride, golden, thorton, panama_city, fruita, gladstone, vernal, gunnison, ridgway, pueblo_west, windsor, kalama, empire, highlands_ranch, aurora, paonia, aspen, mesa, myron, buffdale, parachute, frisco, kremmling, breckenridge, palisade, parker, colorado_springs, hayden, basalt, idaho_springs, farmington, roosevelt, frederick, norwood, ft_lupton, fort_collins, st_augustine, eagle, loveland, englewood, durango, santa_ana, gypsum, longmont, phoenix, brighton, dacono, ouray, los_angelas, wolcott, arvada, littleton, dove_creek, lindon, scottsbluff, oklahoma_city, wood_dale, columbus, herber_city, grand_island, austin, cumming, johnstown, san_diego, stafford, bogart, de_beque, modesto, lehi, champlain, delray_beach, san_fransico, draper, wheat_ridge, yoder, cheyenne, caldwell, moroni, cave_creek, salt_lake_city, tarzana, denton, castle_rock, fargo, kansas_city, hildale, collbran, lakewood, avon, pueblo, garland, greenwood_village, albuquerque, marietta, morrison, belgrade, crawford, troy, sandy, greeley, broomfield, carson, houston, cortez, whitewater, greenville, mchenry, madison, flagstaff, portsmouth, midway, hoboken, cincinnati, monument, little_canada, grand_rapids, cedaredge, glade_park, granby, gentry, provo, casa_grande, west_jordan, gaithersburg, carrollton, farmers_branch, milwaukee, centerville, lake_elmo, dallas, muskego, janesville, cleveland, venus, cerritos, e_setauket, westfield, downey, medina, san_antonio, west_warwick, conway, kent, thousand_palms, walton_hills, londonerry, crown_point, tulsa, snowmass, rangley, ripon, trinidad, phippsburg, crested_butte, leadville]

    [db.session.add(item) for item in list]
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_cities():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.cities RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM cities"))

    db.session.commit()
