from app.models import db, Company, environment, SCHEMA
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_companies():

    # GENERAL CONDITIONS
    aamold_engineering = Company(company_name='Aamold Engineering', address='579 Elkhart Lane', address_2='')
    action_design_construction = Company(company_name='Aamold Engineering', address='579 Elkhart Lane', address_2='')
    all_pro_moving = Company(company_name='All Pro Moving', address='559 Sandhill Lane #202', address_2='')
    areas_best_maintenance = Company(company_name='Areas Best Maintenance', address='P.O. Box 40395', address_2='')
    arches_engineering = Company(company_name='Arches Engineering', address='P.O Box 3852', address_2='2283 Ivory Co...?')
    aspen_earthmoving = Company(company_name='Aspen Earthmoving', address='818 Industrial Way', address_2='')
    avant_environmental_spec = Company(company_name='Avant Environmental Specialists', address='120 Mesa Grande Drive', address_2='')
    bailey_house_movers = Company(company_name='Bailey House Movers', address='3149 B. Road', address_2='')
    bighorn_consulting = Company(company_name='Bighorn Consulting Engineers', address='569 Westgate Drive, Suite 1', address_2='')
    black_diamond = Company(company_name='Black Diamond, Inc.', address='P.O Box 57', address_2='')
    bookcliff_survey_serv = Company(company_name='Bookcliff Survey Services, Inc.', address='136 East Third Street', address_2='')
    bridger_crane_rigging = Company(company_name='Bridger Crane & Rigging, LLC', address='838 - 21 1/2 Road', address_2='')
    buckhorn_geotech = Company(company_name='Buckhorn Geotech', address='222 South Park Avenue', address_2='')
    commercial_refuse = Company(company_name='Commercial Refuse Service', address='', address_2='')
    enterprises_traffic_control = Company(company_name='C C Enterprises Traffic Control SPecialists, Inc.', address='830 21 1/2 Road', address_2='')
    ccs_crane = Company(company_name='CCS Crane', address='4941 Co. Road 346', address_2='')
    cert_business_serv = Company(company_name='Certified Business Services, Inc.', address='6920 South Jordan Road, Suite K', address_2='')
    clymer_trucking = Company(company_name='Clymer Trucking', address='1713 Clymer Way', address_2='')
    cosco_industries = Company(company_name='Cosco Industries', address='West 215 Second Ave.', address_2='')
    crawford_trucking = Company(company_name='Crawford Trucking', address='2702 Hwy 50', address_2='')
    creative_lifting = Company(company_name='Creative Lifting Services, Inc.', address='', address_2='')
    croisant_cleaning = Company(company_name='Croisant Custom Cleaning', address='P.O. Box 189', address_2='')
    cr_surveying = Company(company_name='CR Surveying, LLC', address='717 Centauri Drive', address_2='')
    ctl_thompson = Company(company_name='CTL Thompson', address='1971 W. 12th Ave.', address_2='')
    custom_industries = Company(company_name='Custom Industries, Inc.', address='769 Valley Court', address_2='')
    delmont_consultants = Company(company_name='Del-Mont Consultants, Inc.', address='125 Colorado Ave.', address_2='')
    design_perspectives = Company(company_name='Design Perspectives, Ltd.', address='514 28 1/4 Road, Suite 2', address_2='')
    design_source_west = Company(company_name='Design Source West, Inc.', address='2219 Rimrock Road', address_2='')
    dh_surveys = Company(company_name='DH Surveys, Inc.', address='118 Ouray Ave.', address_2='')
    down_valley_septic = Company(company_name='Down Valley Septic, LLC', address='P.O. Box 1929', address_2='')
    eco_contracting = Company(company_name='ECO Contracting', address='35298 Hanson Mesa Road', address_2='')
    elwood_staffing = Company(company_name='Elwood Staffing (SOS)', address='359 Main Street, Suite 2', address_2='')
    essman_trucking = Company(company_name='Essman Trucking, Inc.', address='', address_2='')
    force_deconstruction = Company(company_name='Force Deconstruction, LLC.', address='9684 Hillside Road', address_2='')
    four_points = Company(company_name='Four Points Surveying & Engineering', address='P.O. Box 775966', address_2='')
    geotech_engineering = Company(company_name='Geotechnical Engineering Group', address='2308 Interstate Ave.', address_2='')
    goodwin_services = Company(company_name='Goodwin Services, Inc.', address='661 - 24 1/2 Road', address_2='')
    grand_river_environ = Company(company_name='Grand River Environmental, LLC', address='562 Huntington Point Lane', address_2='')
    grand_valley_repro = Company(company_name='Grand Valley Reprographics & Survey Supplies', address='565 - 25 Road #110-A', address_2='')
    ground_engineering = Company(company_name='Ground Engineering Consultants, Inc.', address='41 Inverness Drive East', address_2='')
    hawk_contracting = Company(company_name='Hawk Contracting Group, LLC', address='P.O. Box 490', address_2='402 S. 2nd Street')
    hepworth_geotech = Company(company_name='Hepworth-Pawlak Geotechnical, Inc.', address='5020 Country Road 154', address_2='')
    hi_desert = Company(company_name='Hi Desert', address='P.O. Box 537', address_2='')
    high_desert = Company(company_name='High Desert Surveying, LLC', address='1673 Hwy 50, Unit C', address_2='')
    huddleston_engineering = Company(company_name='Huddleston-Berry Engineering & Testing, LLC', address='640 White Ave.', address_2='')
    hy_safe_tech = Company(company_name='Hy-Safe Technology', address='960 Commerce Drive', address_2='')
    industrial_sys = Company(company_name='Industrial Systems, Inc.', address='5513 Hwy. 348', address_2='')
    jk_trucking = Company(company_name='J & K Trucking, LLC', address='3002 I-70 Business Loop, Unit #5', address_2='')
    key_people = Company(company_name='Key People Company', address='', address_2='')
    kn_window = Company(company_name='KN Professional Window Cleaning', address='P.O. Box 2114', address_2='')
    mary_vees_cleaning = Company(company_name='Mary Vees Cleaning', address='447 Sandia Drive', address_2='')
    mcgrath = Company(company_name='McGrath, Inc.', address='5353 W. Dartmouth, Suite 506', address_2='')
    midwest_scafford = Company(company_name='Midwest Scafford Service', address='3975 East 56th Ave.', address_2='')
    mmd_engineering = Company(company_name='MM & D Engineering Services', address='305 1/2 Main Street', address_2='')
    mwe_services = Company(company_name='MWE Services, Inc.', address='1935 Yolande Ave.', address_2='')
    neils_landscape = Company(company_name='Neils Lunceford Landscape Design/Build', address='307 East Capital Court', address_2='')
    phase_environ_consult = Company(company_name='Phase con Environmental Consultants', address='539 - 19 3/4 Road', address_2='')
    pioneer_propane = Company(company_name='Pioneer Propane, Inc.', address='741 - 1325 Road', address_2='')
    polaris_survey = Company(company_name='Polaris Surveying', address='3149 Mesa Ave., Unit B', address_2='')
    powers_ent = Company(company_name='Powers Enterprises, Inc.', address='1790 W. Victory Way', address_2='')
    rifle_works = Company(company_name='Rifle Works', address='124 E. 4th Street', address_2='')
    rw_trucking = Company(company_name='RW Trucking, LLC', address='599 McMullin Drive', address_2='')
    san_juan_surveying = Company(company_name='San Juan Surveying', address='160 Society Drive', address_2='')
    sensera_sys = Company(company_name='Sensera Systems', address='1212 Arapahoe Street', address_2='')
    skch_enterprise = Company(company_name='SKCH Enterprises, Inc.', address='P.O Box 938', address_2='')
    sgm_engineering = Company(company_name='SGM Engineering, Consulting & Surveying', address='118 W. 6th Street, Suite 200', address_2='')
    solar_valley_enterprise = Company(company_name='Solar Valley Enterprises, LLC', address='2618 West 13th', address_2='')
    stanton_engineering = Company(company_name='Stanton Engineering Solutions', address='P.O. Box 2510', address_2='')
    sterling_crane = Company(company_name='Sterling Crane', address='9351 Grant Street, Suite 250', address_2='')
    superior_traffic = Company(company_name='Superior Traffic Control', address='516 Fruitvale Court', address_2='')
    tanglewood = Company(company_name='Tanglewood', address='2355 County Road 226', address_2='')
    terracon = Company(company_name='Terracon', address='2308 Interstate Ave.', address_2='')
    tforce_engergy = Company(company_name='Tforce Energy Services', address='767 Valley Court', address_2='')
    total_personnel = Company(company_name='Total Personnel Management', address='2829 North Ave., Suite 202', address_2='')
    united_rentals = Company(company_name='United Rentals', address='2316 Interstate Ave.', address_2='')
    united_site_services = Company(company_name='United Site Services', address='5 Powerline Road', address_2='')
    united_site_colorado = Company(company_name='United Site Services of Colorado, Inc.', address='P.O. Box 219', address_2='')
    usc_labor_sol = Company(company_name='USC Labor Solutions, Inc.', address='1402 South Mail Street', address_2='')
    xtreme_crane = Company(company_name='Xtreme Crane', address='2701 Caribbean Drive', address_2='')
    yeh_associates = Company(company_name='Yeh & Associates, Inc.', address='588 North Commercial Drive', address_2='')
    your_way_safety = Company(company_name='Your Way Safety & Sign Supply', address='749 Winters Ave.', address_2='')
    zimmermann_construction = Company(company_name='Zimmermann Construction Staffing', address='701 Jenks Ave.', address_2='')


    list_1 = [aamold_engineering, action_design_construction, all_pro_moving, areas_best_maintenance, arches_engineering, aspen_earthmoving, avant_environmental_spec, bailey_house_movers, bighorn_consulting, black_diamond, bookcliff_survey_serv, bridger_crane_rigging, buckhorn_geotech, commercial_refuse, enterprises_traffic_control, ccs_crane, cert_business_serv, clymer_trucking, cosco_industries, crawford_trucking, creative_lifting, croisant_cleaning, cr_surveying, ctl_thompson, custom_industries, delmont_consultants, design_perspectives, design_source_west, dh_surveys, down_valley_septic, eco_contracting, elwood_staffing, essman_trucking, force_deconstruction, four_points, geotech_engineering, goodwin_services, grand_river_environ, grand_valley_repro, ground_engineering, hawk_contracting, hepworth_geotech, hi_desert, high_desert, huddleston_engineering, hy_safe_tech, industrial_sys, jk_trucking, key_people, kn_window, mary_vees_cleaning, mcgrath, midwest_scafford, mmd_engineering, mwe_services, neils_landscape, phase_environ_consult, pioneer_propane, polaris_survey, powers_ent, rifle_works, rw_trucking, san_juan_surveying, sensera_sys, skch_enterprise, sgm_engineering, solar_valley_enterprise, stanton_engineering, sterling_crane, superior_traffic, tanglewood, terracon, tforce_engergy, total_personnel, united_rentals, united_site_services, united_site_colorado, usc_labor_sol, xtreme_crane, yeh_associates, your_way_safety, zimmermann_construction]


    # SITE CONSTRUCTION
    accurate_construction = Company(company_name='Accurate Construction & Excavation', address='P.O. Box 667', address_2='')
    adf_west = Company(company_name='ADF West, Inc.', address='7608 N. Kansas Ave.', address_2='')
    allred_paving = Company(company_name='Allred Paving', address='3996 W. 1500 N.', address_2='')
    all_service_septic = Company(company_name='All Service Septic', address='P.O. Box 2844', address_2='')
    alvin_landis = Company(company_name='Alvin L. Landis Contractor, Inc.', address='P.O. 4388', address_2='')
    a_maes_ing = Company(company_name='A-Maes-ing Landscape & Grounds Maintenance', address='2981 Brookside Drive', address_2='')
    armor_proseal = Company(company_name='Armor Proseal', address='3518 Congress Street', address_2='')
    arnies_excavating = Company(company_name='Arnie\'s Excavating', address='407 N. 7th Street', address_2='')
    artificial_turf = Company(company_name='Artificial Turf Supply', address='', address_2='')
    atlas_construction = Company(company_name='Atlas Construction', address='587 Health Drive', address_2='')
    avalon_landscaping = Company(company_name='Avalon Landscaping & Maintenance', address='312 East Highland Drive', address_2='')
    asphalt_specialists = Company(company_name='Asphalt Specialists Supply, Inc.', address='2462 Industrial Blvd.', address_2='')
    bolinger_queen = Company(company_name='Bolinger & Queen', address='32874 J Rd.', address_2='')
    ben_dowd_excav = Company(company_name='Ben Dowd Excavating', address='550 32 Road', address_2='')
    bookcliff_gardens = Company(company_name='Bookcliff Gardens', address='755 26 Road', address_2='')
    busy_beaver_landscaping = Company(company_name='Busy Beaver Landscaping', address='530 34 Road', address_2='')
    canyon_excavation = Company(company_name='Canyon Excavating', address='545 Canyon Creek Drive', address_2='')
    choate_excavating = Company(company_name='Choate Excavating', address='101 Fisher Canyon Drive', address_2='')
    clarke_co = Company(company_name='Clarke & Co.', address='3017 Highway 50', address_2='')
    co_asphalt_sealcoating = Company(company_name='Colorado Asphalt Sealcoating & Landscaping', address='', address_2='')
    co_asphalt_main = Company(company_name='Colorado Asphalt Maintenance', address='610 -33 Road', address_2='')
    co_grouting = Company(company_name='Colorado Grouting, Inc.', address='1867 E. Platteville Blvd.', address_2='')
    co_piling = Company(company_name='Colorado Piling Service', address='P.O. Box 1824', address_2='')
    coloscapes_concrete = Company(company_name='Coloscapes Concrete', address='P.O. Box 207', address_2='')
    co_west_contracting = Company(company_name='Colorado West Contracting, Inc.', address='241 -31 3/10 Road', address_2='')
    crazy_final_touch = Company(company_name='Crazy 8 The Final Touch', address='', address_2='')
    cw_construction = Company(company_name='CW Construction', address='433 Keener Street', address_2='')
    dale_quality_land = Company(company_name='Dale\'s Quality Landscaping', address='629 Braemer Circle', address_2='')
    deep_creek = Company(company_name='Deep Creek, Inc.', address='840 23 1/2 Road', address_2='')
    dependable_land = Company(company_name='Dependable Landscaping', address='1752 L 1/2 Road', address_2='')
    dj_landscaping = Company(company_name='DJ\'s Landscaping', address='', address_2='')
    downing_diversified = Company(company_name='Downing Diversified', address='P.O. Box 33', address_2='447 N. First St.')
    down_to_earth = Company(company_name='Down To Earth Compliance', address='2460 S. Syracuse Way', address_2='')
    dynamic_hardscape = Company(company_name='Dynamic Hardscape in Landscaping, LLC', address='127 22 Court', address_2='')
    eagles_nest_contract = Company(company_name='Eagles Nest Contracting', address='189 Sun Hawk Drive', address_2='')
    elam_construction = Company(company_name='Elam Contruction', address='556 Struthers Avenue', address_2='')
    elite_field_services = Company(company_name='Elite Field Services, LLC', address='377 Indian Road', address_2='')
    empire_demo = Company(company_name='Empire Demolition & Property Services, LLC', address='P.O. Box 432', address_2='')
    england_fence = Company(company_name='England Fence Company', address='1568 N. Townsend Ave.', address_2='')
    environ_connection = Company(company_name='Environmental Connection, LLC', address='10296 Cherryhurst Ln.', address_2='')
    excel_environ = Company(company_name='Excel Environmental, Inc.', address='1852 Jasper Street, Unit E', address_2='')
    farmsworth_construction = Company(company_name='Farmsworth Construction & Gravel Co.', address='175 Hwy 133', address_2='')
    filter_tech = Company(company_name='Filter Tech Systems, Inc.', address='2844 Chipeta Ave.', address_2='')
    flattop_steel = Company(company_name='Flattop Steel Piering', address='1171 16 Road', address_2='')
    four_evergreen_land = Company(company_name='4 Evergreen Landscape (DO NOT USE)', address='516 1/2 Florence Road', address_2='')
    four_seasons_main = Company(company_name='Four Seasons Property Maintenance & Landscape', address='P.O. Box 9545', address_2='')
    frontier_paving = Company(company_name='Frontier Paving', address='P.O. Box 1167', address_2='854 Bedrock...?')
    g_g_paving = Company(company_name='G & G Paving Construction, Inc.', address='1005 N. 12th Street', address_2='')
    grade_plus = Company(company_name='Grade Plus, Inc.', address='P.O. Box 40722', address_2='')
    grand_junc_ready_mix = Company(company_name='Grand Junction Ready Mix', address='P.O. Box 1849', address_2='')
    great_divide_earth = Company(company_name='Great Divide Earthworks', address='1950 Timber Falls Drive', address_2='')
    gross_excavating = Company(company_name='Gross Excavating, Inc.', address='P.O. Box 417', address_2='')
    gunnison_construc = Company(company_name='Gunnison Construction & Septic', address='720 S. 8th Street', address_2='')
    gunnison_gravel = Company(company_name='Gunnison Gravel & Earthmoving', address='P.O. Box 42', address_2='')
    hawk_excavation = Company(company_name='Hawk Excavation & Construction', address='P.O. Box 379', address_2='')
    hi_river_construc = Company(company_name='Hi River Construction, Inc.', address='P.O. Box 55116', address_2='')
    hill_builders = Company(company_name='Hill Builders, Inc.', address='3762 Highway 82, Suite 2', address_2='')
    intermountain_helical = Company(company_name='Intermountain Helical Piers', address='14712 So. Heritage Crest Way', address_2='')
    intermountain_landscape = Company(company_name='Intermountain Landscape & Sprinkler, Inc.', address='17000 S. Golden Road, Suite 101', address_2='')
    j_c_excavating = Company(company_name='J C Excavating, Inc.', address='600 Cardinal Way', address_2='')
    jmi_excavating = Company(company_name='JMI Excavating', address='4595 Country Road 10', address_2='')
    kb_construction = Company(company_name='KB Construction & Excavation, Inc.', address='P.O. Box 4008', address_2='')
    k_d_construction = Company(company_name='K & D Construction', address='', address_2='')
    kr_swerdfeger = Company(company_name='K.R. Swerdfeger Construction, Inc.', address='421 East Industrial Blvd.', address_2='')
    kumar_associates = Company(company_name='Kumar & Associates, Inc.', address='319 S. 3rd St.', address_2='')
    landscape_tech = Company(company_name='Landscape Technologies, Inc.', address='P.O. Box 486', address_2='')
    m_m_excavation = Company(company_name='M & M Excavation', address='P.O. Box 174', address_2='')
    m_a_concrete = Company(company_name='M A Concrete Construction', address='P.O. Box 1968', address_2='')
    maple_leaf_landscape = Company(company_name='Maple Leaf Landscaping & Maintenance, Inc.', address='197 Sun Hawk Drive', address_2='')
    martin_construction = Company(company_name='Martin Construction, Co.', address='1026 19 1/2 Road', address_2='')
    maximum_services = Company(company_name='Maximum Services', address='P.O. Box 695', address_2='')
    mays_concrete = Company(company_name='May\'s Concrete, Inc.', address='2399 River Road', address_2='')
    mays_construction = Company(company_name='May\'s Construction Specialties', address='P.O. Box 4229', address_2='')
    meeker_sand_gravel = Company(company_name='Meeker Sand & Gravel, Inc.', address='', address_2='')
    metro_fence_company = Company(company_name='Metro Fence Company, Inc.', address='8335 Quebec Street', address_2='')
    metzger_brothers_concrete = Company(company_name='Metzger Brothers Concrete', address='P.O. Box 1076', address_2='')
    misty_mountain_sprink = Company(company_name='Misty Mountain Sprinkler Systems (WOE)', address='1808 Story Lane', address_2='')
    mountain_valley_contract = Company(company_name='Mountain Valley Contracting', address='605 -28 1/4 Road, Suite B', address_2='')
    munro_supply = Company(company_name='Munro Supply, Inc.', address='P.O. Box 519', address_2='')
    neils_lunceford = Company(company_name='Neils Lunceford, Inc.', address='P.O. Box 2130', address_2='740 Blue River...?')
    northwest_ready_mix = Company(company_name='Northwest Ready Mix, Inc.', address='2930 E. Hwy 40', address_2='')
    oec_construction = Company(company_name='OEC Construction (OUT OF BUSINESS?)', address='1100 Fruit Park Trail', address_2='')
    old_castle = Company(company_name='Old Castle', address='', address_2='')
    olsson_associates = Company(company_name='Olsson Associates', address='760 Horizon Drive, Suite 102', address_2='')
    on_grade_excavation = Company(company_name='On Grade Excavation', address='2811 Patterson Road', address_2='')
    palisade_constructors = Company(company_name='Palisade Constructors, Inc. (DO NOT USE)', address='695 36 Road', address_2='')
    paragon_excavating = Company(company_name='Paragon Excavating Services', address='P.O. Box 1432', address_2='')
    parkerson_construction = Company(company_name='Parkerson Construction', address='710 S. 15th Street', address_2='')
    patriot_highway_markings = Company(company_name='Patriot Highway Markings', address='P.O. Box 1628', address_2='')
    penley_concrete = Company(company_name='Penley Concrete & Caisson Drilling', address='P.O. Box 759', address_2='')
    professional_pipe_concrete = Company(company_name='Professional Pipe & Concrete', address='', address_2='')
    quality_underground = Company(company_name='Quality Underground', address='3785 Interpark Drive', address_2='')
    rainbow_valley_asphalt = Company(company_name='Rainbow Valley Asphalt', address='1920 M. Road', address_2='')
    rainmaker = Company(company_name='Rainmaker, Inc.', address='17656 Highway 550', address_2='')
    rdc_inc = Company(company_name='RDC, Inc.', address='40320 CR 80', address_2='')
    rex_phelps = Company(company_name='Rex Phelps for Landscaping & Irrigation', address='372 29 5/8 Road', address_2='')
    rocky_mountain_civil = Company(company_name='Rocky Mountain Civil, Inc.', address='2875 C 1/2 Road #6', address_2='')
    rocky_mountain_rebar = Company(company_name='Rocky Mountain Rebar, H & H Bolt', address='686 Industrial Blvd.', address_2='')
    roop_excavating = Company(company_name='Roop Excavating', address='39585 Lund Road', address_2='')
    sako_excavation = Company(company_name='Sako Excavation', address='1254 Country Road', address_2='')
    savage_excavation = Company(company_name='Savage Excavation', address='P.O. Box 2916', address_2='')
    sheridan_mountain_excavation = Company(company_name='Sheridan Mountain Excavation, LLC', address='P.O. Box 1933', address_2='300 Whitehoc...?')
    skyline_contracting = Company(company_name='Skyline Contracting', address='3191 Mesa Avenue', address_2='')
    sky_ute_sand = Company(company_name='Sky Ute Sand & Gravel', address='P.O. Box 2270', address_2='')
    sorter_construction = Company(company_name='Sorter Construction, Inc.', address='2802 Highway 50', address_2='')
    southwest_soils = Company(company_name='Southwest Soils / Pioneer Sand', address='58521 Amber Road', address_2='')
    straight_edge_striping = Company(company_name='Straight Edge Striping', address='3019 D 1/2 Road', address_2='')
    tallgrass_landscape = Company(company_name='Tallgrass Landscape & Construction', address='', address_2='')
    tally_ho_construction = Company(company_name='Tally Ho Construction', address='0145 County Road 225', address_2='')
    taylor_fence_denver = Company(company_name='Taylor Fence Company of Denver', address='2531 West 62nd Court, Unit H', address_2='')
    taylor_fence_gj = Company(company_name='Taylor Fence Company of Grand Junction', address='P.O. Box 3125', address_2='')
    td_hydro_vac = Company(company_name='TD Hydro Vac', address='747 Buckhorn Drive', address_2='')
    landscape_center = Company(company_name='The Landscape Center', address='2523 High Country Court', address_2='')
    three_acres_landscape = Company(company_name='Three Acres Landscaping (OUT OF BUSINESS)', address='516 Fruitvale Court, Suite A', address_2='')
    trench_shoring = Company(company_name='Trench Shoring Services', address='3174 Perkins Drive', address_2='')
    tuff_excavation = Company(company_name='Tuff Excavation, Inc.', address='3498 E. 3500 S.', address_2='')
    ty_striping = Company(company_name='Ty Striping', address='1330 N. 17th Street', address_2='')
    unitah_basin_lawn = Company(company_name='Unitah Basin Lawn & Landscaping', address='4464 W. 3000 S.', address_2='')
    united_companies = Company(company_name='United Companies', address='21830 U.S 550', address_2='')
    united_paving = Company(company_name='United Paving', address='2273 River Road', address_2='')
    united_redi_mix = Company(company_name='United Redi-Mix Concrete', address='P.O. Box 3609', address_2='')
    upland_companies = Company(company_name='Upland Companies', address='P.O. Box 1380', address_2='')
    valley_excavating_glenwood = Company(company_name='Valley Excavating of Glenwood', address='192 Ponderosa Drive', address_2='')
    valley_wide_fence = Company(company_name='Valley Wide Fence', address='2105 East Main Street', address_2='')
    vista_paving_corp = Company(company_name='Vista Paving Corporation', address='1000 N. 9th Street, #27', address_2='')
    wagner_construction = Company(company_name='Wagner Construction, Inc.', address='1850 East 1st Street', address_2='')
    wd_yards = Company(company_name='WD Yards', address='577 N. Westgate Drive', address_2='')
    western_piling = Company(company_name='Western Piling & Caisson, Inc.', address='P.O. Box 2052', address_2='')
    western_pipeline_util = Company(company_name='Western Pipeline Utilities Construction, Inc.', address='3643 Front Street', address_2='')
    western_states_reclam = Company(company_name='Western States Reclamation, Inc.', address='3756 Imperial Street', address_2='')
    white_mountain_operating = Company(company_name='White Mountain Operating', address='601 Silver Plume Drive', address_2='')
    white_water_building = Company(company_name='White Water Building Materials', address='P.O. Box 1769', address_2='')
    williams_construction = Company(company_name='Williams Construction', address='P.O. Box 704', address_2='')
    wilson_backhoe_service = Company(company_name='Wilson Backhoe Service', address='3115 C Road', address_2='')
    wishbone_hoe_service = Company(company_name='Wishbone Hoe Service', address='162 Drumlin Circle', address_2='')
    yenter_companies = Company(company_name='Yenter Companies', address='2388 Leland Ave.', address_2='')


    list_2 = [accurate_construction, adf_west, allred_paving, all_service_septic, alvin_landis, a_maes_ing, armor_proseal, arnies_excavating, artificial_turf, atlas_construction, avalon_landscaping, asphalt_specialists, bolinger_queen, ben_dowd_excav, bookcliff_gardens, busy_beaver_landscaping, canyon_excavation, choate_excavating, clarke_co, co_asphalt_sealcoating, co_asphalt_main, co_grouting, co_piling, coloscapes_concrete, co_west_contracting, crazy_final_touch, cw_construction, dale_quality_land, deep_creek, dependable_land, dj_landscaping, downing_diversified, down_to_earth, dynamic_hardscape, eagles_nest_contract, elam_construction, elite_field_services, empire_demo, england_fence, environ_connection, excel_environ, farmsworth_construction, filter_tech, flattop_steel, four_evergreen_land, four_seasons_main, frontier_paving, g_g_paving, grade_plus, grand_junc_ready_mix, great_divide_earth, gross_excavating, gunnison_construc, gunnison_gravel, hawk_excavation, hi_river_construc, hill_builders, intermountain_helical, intermountain_landscape, j_c_excavating, jmi_excavating, kb_construction, k_d_construction, kr_swerdfeger, kumar_associates, landscape_tech, m_m_excavation, m_a_concrete, maple_leaf_landscape, martin_construction, maximum_services, mays_concrete, mays_construction, meeker_sand_gravel, metro_fence_company, metzger_brothers_concrete, misty_mountain_sprink, mountain_valley_contract, munro_supply, neils_lunceford, northwest_ready_mix, oec_construction, old_castle, olsson_associates, on_grade_excavation, palisade_constructors, paragon_excavating, parkerson_construction, patriot_highway_markings, penley_concrete, professional_pipe_concrete, quality_underground, rainbow_valley_asphalt, rainmaker, rdc_inc, rex_phelps, rocky_mountain_civil, rocky_mountain_rebar, roop_excavating, sako_excavation, savage_excavation, sheridan_mountain_excavation, skyline_contracting, sky_ute_sand, sorter_construction, southwest_soils, straight_edge_striping, tallgrass_landscape, tally_ho_construction, taylor_fence_denver, taylor_fence_gj, td_hydro_vac, landscape_center, three_acres_landscape, trench_shoring, tuff_excavation, ty_striping, unitah_basin_lawn, united_companies, united_paving, united_redi_mix, upland_companies, valley_excavating_glenwood, valley_wide_fence, vista_paving_corp, wagner_construction, wd_yards, western_piling, western_pipeline_util, western_states_reclam, white_mountain_operating, white_water_building, williams_construction, wilson_backhoe_service, wishbone_hoe_service, yenter_companies]


    # CONCRETE
    a_s_sandblasting = Company(company_name='A & S Sandblasting & Coating, LLC', address='2488 Commerce Blvd', address_2='')
    accurate_concrete = Company(company_name='Accurate Concrete Cutting, Inc.', address='1133 23 1/2 Road', address_2='')
    ach_foam_tech = Company(company_name='ACH Foam Technologies, LLC', address='5250 N. Sherman Street', address_2='')
    adcock_concrete = Company(company_name='Adcock Concrete', address='2458 Industrial Blvd., Suite 1', address_2='')
    advanced_concrete_co = Company(company_name='Advanced Concrete of Colorado', address='170 T2 Trail', address_2='')
    aleman_concrete = Company(company_name='Aleman Concrete', address='1061 W. Beaver Creek Blvd.', address_2='')
    architectural_concrete = Company(company_name='Architectural Concrete Finishes', address='P.O. Box 1342', address_2='')
    arco_concrete = Company(company_name='ARCO Concrete, Inc.', address='12672 WCR 6 1/4', address_2='')
    bear_concrete = Company(company_name='Bear Concrete', address='2243 Wakefield Drive', address_2='')
    brundage_bone_concrete = Company(company_name='Brundage-Bone Concrete Pumping', address='', address_2='')
    beyond_your_ordinary = Company(company_name='Beyond Your Ordinary Recreation', address='405 Golfway West Drive, Suite 302', address_2='')
    burner_construction = Company(company_name='Burner Construction, LLC', address='118 North Willow Street', address_2='')
    calco_concrete = Company(company_name='Calco Concrete Pumping, Inc.', address='P.O. Box 3775', address_2='')
    carver_brothers = Company(company_name='Carver Brothers, Inc.', address='P.O. Box 175', address_2='')
    co_concrete = Company(company_name='Colorado Concrete Accessories', address='2474 Industrial Blvd.', address_2='')
    co_precast = Company(company_name='Colorado Precast Concrete', address='1820 E. Hwy 402', address_2='')
    concrete_equip_supply = Company(company_name='Concrete Equipment & Supply', address='145 W. Main', address_2='')
    concrete_floor_sys = Company(company_name='Concrete Floor Systems, LLC', address='2051 W. College Ave.', address_2='')
    concrete_sys = Company(company_name='Concrete Systems, Inc.', address='881 Bidwell Ave.', address_2='')
    contracting_specialties = Company(company_name='Contracting Specialties', address='93 Silver Trails Rd.', address_2='')
    copeland_concrete = Company(company_name='Copeland Concrete, Inc.', address='28803 Hwy. 6', address_2='')
    crm_concrete = Company(company_name='CRM Concrete, Inc.', address='922 - 20 Road', address_2='')
    cutting_edge_concrete = Company(company_name='Cutting Edge Concrete Sawing', address='P.O. Box 40341', address_2='')
    dalco = Company(company_name='Dalco', address='3730 Salem Street', address_2='')
    eagle_valley_found = Company(company_name='Eagle Valley Foundations', address='189 Spring Creek Road', address_2='')
    ecs_corp = Company(company_name='ECS Corporation', address='2678 Hwy. 50', address_2='')
    fitzgerald_formliners = Company(company_name='Fitzgerald Formliners', address='1500 E. Chestnut Ave', address_2='')
    fruita_grand_junc_body = Company(company_name='Fruita Grand Junction Body & Paint, Inc.', address='', address_2='')
    gary_rinderle_construction = Company(company_name='Gary Rinderle Construction, Inc.', address='P.O. Box 1380', address_2='')
    gonzales_construction = Company(company_name='Gonzales Concrete Construction', address='960 - 20 1/2 Road', address_2='')
    hawxby_concrete = Company(company_name='Hawxby Concrete', address='103 Brown Road', address_2='')
    hcc_flooring = Company(company_name='HCC Flooring Solutions', address='715 N. Ventura Street', address_2='')
    high_con_inc = Company(company_name='High-Con, Inc.', address='100 Elk Run Drive', address_2='')
    highline_concrete_pumping = Company(company_name='Highline Concrete Pumping, LLC', address='P.O. Box 1022', address_2='')
    hooper_sons_concrete = Company(company_name='Hooper & Sons Concrete, Inc.', address='634 E. 250 N.', address_2='')
    k_g_rebar = Company(company_name='K & G Rebar, LLC', address='4491 - 5950 Road', address_2='')
    k_k_concrete = Company(company_name='K & K Concrete, Inc.', address='P.O. Box 578', address_2='')
    lawson_construction = Company(company_name='Lawson Construction', address='P.O. Box 1318', address_2='20 South Sun')
    lm_scofield_comp = Company(company_name='L.M Scofield Company', address='1710 East Mountain Sky Ave.', address_2='')
    lms_drilling = Company(company_name='LMS Drilling, Inc.', address='10420 E. 107th Place', address_2='')
    mm_concrete_construction = Company(company_name='M & M Concrete Construction, Inc.', address='384 - 27 1/2 Road', address_2='')
    mountain_concrete = Company(company_name='Mountain Concrete', address='615 Mountain View Road', address_2='')
    new_millennium_concrete = Company(company_name='New Millennium Concrete', address='237 Arroya Drive', address_2='')
    nimthor_inc = Company(company_name='Nimthor, Inc.', address='686 Industrial Boulevard', address_2='')
    octaform_systems = Company(company_name='Octaform Systems, Inc.', address='520 - 885 Dunsmuir Street', address_2='')
    preferred_denver = Company(company_name='Preferred Denver, LLC', address='7245 Gilpin Way, Suite 230', address_2='')
    r_r_concrete_pumping = Company(company_name='R & R Concrete Pumping, LLC', address='170 TX Trail', address_2='')
    rcd_construction = Company(company_name='R.C.D. Construction', address='P.O. Box 322', address_2='')
    reliance_precast = Company(company_name='Reliance Precast, LLC', address='4558 Grand View Blvd.', address_2='')
    r_c_concrete = Company(company_name='R & C Concrete, LLC', address='358 - 5th Street', address_2='')
    rms_concrete = Company(company_name='RMS Concrete', address='P.O. Box 670', address_2='6702 Hwy. 82')
    rodco_concrete = Company(company_name='Rodco Concrete, LLC', address='P.O. Box 304', address_2='')
    s2m_construction = Company(company_name='S2M Construction, Inc.', address='P.O. Box 1578', address_2='282 Center Drive')
    speedys_concrete = Company(company_name='Speedy\'s Concrete', address='135 Fedel Ct.', address_2='')
    star_precast_concrete = Company(company_name='Star Precast Concrete', address='1500 County Road 259', address_2='135 River Fro...?')
    stearns_construction = Company(company_name='Stearns Construction, Inc.', address='2746 Pebble Acres Drive', address_2='')
    straight_line_construction = Company(company_name='Straight Line Construction Co.', address='94 N. Mission Drive', address_2='')
    summit_concrete = Company(company_name='Summit Concrete', address='', address_2='')
    surevoid_products = Company(company_name='SureVoid Products, Inc.', address='1895 W. Dartmouth Ave.', address_2='')
    t_c_concrete = Company(company_name='T & C Concrete', address='P.O. Box 126', address_2='')
    tdm_concrete = Company(company_name='TDM Concrete', address='1277 Satitarius Street', address_2='')
    tennant_company = Company(company_name='Tennant Company - Architectural Coatings', address='1311 Beverly Green Drive', address_2='')
    williams_industrial_coat = Company(company_name='Williams Industrial Coatings, LLC', address='524 Garnet Drive', address_2='')
    zaabadick_construction = Company(company_name='Zaabadick Construction', address='710 Sierra Vista Way', address_2='')


    list_3 = [a_s_sandblasting, accurate_concrete, ach_foam_tech, adcock_concrete, advanced_concrete_co, aleman_concrete, architectural_concrete, arco_concrete, bear_concrete, brundage_bone_concrete, beyond_your_ordinary, burner_construction, calco_concrete, carver_brothers, co_concrete, co_precast, concrete_equip_supply, concrete_floor_sys, concrete_sys, contracting_specialties, copeland_concrete, crm_concrete, cutting_edge_concrete, dalco, eagle_valley_found, ecs_corp, fitzgerald_formliners, fruita_grand_junc_body, gary_rinderle_construction, gonzales_construction, hawxby_concrete, hcc_flooring, high_con_inc, highline_concrete_pumping, hooper_sons_concrete, k_g_rebar, k_k_concrete, lawson_construction, lm_scofield_comp, lms_drilling, mm_concrete_construction, mountain_concrete, new_millennium_concrete, nimthor_inc, octaform_systems, preferred_denver, r_r_concrete_pumping, rcd_construction, reliance_precast, r_c_concrete, rms_concrete, rodco_concrete, s2m_construction, speedys_concrete, star_precast_concrete, stearns_construction, straight_line_construction, summit_concrete, surevoid_products, t_c_concrete, tdm_concrete, tennant_company, williams_industrial_coat, zaabadick_construction]


    # MASONRY
    allens_masonry = Company(company_name='Allen\'s Masonry Company', address='P.O. Box 69', address_2='')
    alpine_meadow_mason = Company(company_name='Alpine Meadow Masonry, Inc.', address='P.O. Box 197', address_2='')
    ammex_masonry = Company(company_name='Ammex Masonry, Inc.', address='P.O. Box 1272', address_2='')
    asco_masonry = Company(company_name='ASCO Masonry & Construction, LLC', address='2140 Broadway, #101', address_2='')
    berich_masonry = Company(company_name='Berich Masonry Mountain Division', address='P.O. Box 3207', address_2='')
    bg_harrison_mason = Company(company_name='B.G. Harrison Masonry, Inc.', address='389 Roberts Court', address_2='')
    brickstone_inc = Company(company_name='Brickstone, Inc.', address='17921 West 77th Drive', address_2='')
    c_m_enterprises = Company(company_name='C & M Enterprises', address='64275 Oakland Road', address_2='')
    central_masonry = Company(company_name='Central Masonry Corp.', address='8159 Brandon Drive', address_2='')
    collins_corp = Company(company_name='Collins Corporation', address='1850 Launa Drive, #7', address_2='')
    grasso_masonry = Company(company_name='Grasso Masonry, Inc.', address='P.O. Box 2643', address_2='721 Arrowest...?')
    hankins_stone = Company(company_name='Hankins Stone Company', address='P.O. Box 164', address_2='')
    heritage_masonry = Company(company_name='Heritage Masonry, LLC', address='P.O. Box 996', address_2='')
    ims_masonry = Company(company_name='IMS Masonry, Inc.', address='335 South 1250 West', address_2='')
    infintity_surfaces = Company(company_name='Infinity Surfaces, Inc.', address='587 1/2 N. Westgate Drive', address_2='')
    knifer_masonry = Company(company_name='Knifer Masonry', address='130 Columbia Way', address_2='')
    le_dangler_masonry = Company(company_name='LE Dangler Masonry', address='3147 B Road', address_2='')
    lone_rock_mason = Company(company_name='Lone Rock Masonry, LLC', address='3952 Heartherglenn Lane', address_2='')
    markely_construction = Company(company_name='Markely Construction Company, LLC', address='6456 S. Quebec Street, Suite 25', address_2='')
    moore_masonry = Company(company_name='Moore Masonry, LLC', address='1680 M Road', address_2='')
    mountain_view_surfaces = Company(company_name='Mountain View Surfaces', address='255 E. 2nd Street', address_2='P.O. Box 957...?')
    peterson_masonry = Company(company_name='Peterson Masonry', address='P.O. Box 489', address_2='')
    procoat_roof_depot = Company(company_name='ProCoat / Roof Depot', address='4343 Holly Street', address_2='')
    ray_ball_masonry = Company(company_name='Ray Ball Masonry, LLC', address='2272 Paintbrush Court', address_2='')
    rivera_masonry = Company(company_name='Rivera Masonry', address='2371 Rana Road', address_2='')
    rni_masonry = Company(company_name='RNI Masonry', address='P.O. Box 653', address_2='')
    robert_stone = Company(company_name='Robert Stone, Inc.', address='2317 Interstate Ave.', address_2='')
    robinson_brick = Company(company_name='Robinson Brick - General Shale', address='2122 Hwy. 6 & 50', address_2='')
    santos_stone_mason = Company(company_name='Santos Stone Masonry', address='2388 State Highway 135, Lot #12', address_2='')
    scarbrough_construction = Company(company_name='Scarbrough Construction', address='2508 Van Buren Ave.', address_2='')
    specialty_wall_systems = Company(company_name='Specialty Wall Systems', address='', address_2='')
    stonebilt = Company(company_name='StoneBilt', address='2311 River Road', address_2='')
    trig_masonry = Company(company_name='Trig Masonry / Durango Plastering', address='P.O. Box 578', address_2='')


    list_4 = [allens_masonry, alpine_meadow_mason, ammex_masonry, asco_masonry, berich_masonry, bg_harrison_mason, brickstone_inc, c_m_enterprises, central_masonry, collins_corp, grasso_masonry, hankins_stone, heritage_masonry, ims_masonry, infintity_surfaces, knifer_masonry, le_dangler_masonry, lone_rock_mason, markely_construction, moore_masonry, mountain_view_surfaces, peterson_masonry, procoat_roof_depot, ray_ball_masonry, rivera_masonry, rni_masonry, robert_stone, robinson_brick, santos_stone_mason, scarbrough_construction, specialty_wall_systems, stonebilt, trig_masonry]


    # STEEL
    abc_supply = Company(company_name='ABC Supply Co., Inc.', address='1110 Kimball Ave.', address_2='')
    alliance_steel = Company(company_name='Alliance Steel Building Systems', address='3333 South Council Road', address_2='')
    all_metals_welding = Company(company_name='All Metals Welding', address='1707 1-70 Business Loop', address_2='')
    all_steel = Company(company_name='All Steel, Inc.', address='8498 - 61 1/2 Road', address_2='')
    american_standard_steel = Company(company_name='American Standard Steel Building Systems', address='P.O. Box 110602', address_2='')
    artec = Company(company_name='Artec', address='700 Creel Drive', address_2='')
    b_c_steel_corp = Company(company_name='B & C Steel Corp.', address='P.O. Box 1099', address_2='')
    behlen_building = Company(company_name='Behlen Building Systems', address='4025 E. 23rd Street', address_2='')
    bishop_welding_fabrication = Company(company_name='Bishop Welding & Fabrication', address='3139 A 1/2 Road', address_2='')
    blaze_constructors = Company(company_name='Blaze Constructors', address='', address_2='')
    braemar_building = Company(company_name='Braemar Building Systems', address='925 West Kenyon Ave., Suite 6', address_2='')
    butler_manufacturing = Company(company_name='Butler Manufacturing', address='1235 S. 4370 E.', address_2='')
    ceco_building_systems = Company(company_name='Ceco Building Systems', address='5942 Nicklaus Drive', address_2='')
    chief_buildings = Company(company_name='Chief Buildings', address='3942 W. Old Highway 30', address_2='')
    c_l_welding = Company(company_name='C & L Welding', address='20726 Fairview Road', address_2='')
    cladding_component_sol = Company(company_name='Cladding & Component Solutions, Inc.', address='2705 Northgate Court', address_2='')
    clemmer_welding = Company(company_name='Clemmer Welding, LLC', address='714 Arrowest Court', address_2='')
    collins_metal_design = Company(company_name='Collins Metal Design, LLC', address='', address_2='')
    contact_welding_services = Company(company_name='Contact Welding Services, Inc.', address='2907 Hill Ave.', address_2='')
    custom_structural_steel = Company(company_name='Custom Structural Steel, Inc.', address='P.O. Box 1017', address_2='4941 B Count...?')
    division_iv = Company(company_name='Division IV, Inc.', address='2925 58th Avenue', address_2='')
    dmd_fab = Company(company_name='DMD Fab, LLC', address='4255 South Buckley Road, Suite 212', address_2='')
    dons_welding = Company(company_name='Don\'s Welding, LLC', address='869 - 18 1/2 Road', address_2='')
    doughty_steel_machine = Company(company_name='Doughty Steel & Machine', address='P.O. Box 690', address_2='')
    duane_phipps = Company(company_name='Duane Phipps', address='491 - 28 1/2 Road', address_2='')
    dw_metal_works = Company(company_name='DW Metal Works', address='725 Scarlet Drive', address_2='')
    dynamic_metal_works = Company(company_name='Dynamic Metal Works', address='7620 County Road 1', address_2='')
    empire_steel_buildings = Company(company_name='Empire Steel Buildings', address='5230 Carroll Canyon Road, #300', address_2='')
    fast_e_nal = Company(company_name='Fast-e-nal Erectors', address='', address_2='')
    foundation_repair_western_co = Company(company_name='Foundation Repair of Western Colorado, LLC', address='121 Chipeta Ave.', address_2='')
    freedom_steel_buildings = Company(company_name='Freedom Steel Buildings', address='', address_2='')
    frontier_steel_building = Company(company_name='Frontier Steel Building Corp.', address='10940 S. Parker Road', address_2='')
    garfield_steel_machine = Company(company_name='Garfield Steel & Machine, Inc.', address='1815 Airport Road', address_2='')
    greylen_steel_buildings = Company(company_name='Greylen Steel Buildings', address='925 Niagara Street, Suite 230', address_2='')
    industrial_systems = Company(company_name='Industrial Systems', address='P.O. Box 532', address_2='')
    insulated_panel_systems = Company(company_name='Insulated Panel Systems', address='P.O. Box 968', address_2='')
    iron_man_mize = Company(company_name='Iron Man Mize, LLC', address='2200 Moores Ford Road', address_2='')
    iron_monkey_metal = Company(company_name='Iron Monkey Metal Works', address='P.O. Box 368', address_2='')
    keystone_custom_builders = Company(company_name='Keystone Custom Builders, Inc.', address='P.O. Box 1807', address_2='')
    kingspan = Company(company_name='Kingspan', address='2000 Morgan Road', address_2='')
    j_m_steel_sol = Company(company_name='J & M Steel Solutions, Inc.', address='894 West State Street', address_2='')
    leachs_industrial_service = Company(company_name='Leach\'s Industrial Service, Inc.', address='2508 Industrial Court', address_2='')
    mach2_construction = Company(company_name='Mach2 Construction', address='P.O. Box 1609', address_2='')
    mackey_metal_roofing = Company(company_name='Mackey Metal Roofing, Inc.', address='417 State Route 11, Suite 235', address_2='')
    metal_building_services = Company(company_name='MBS (Metal Building Services, LLC)', address='9382 E. Pioneer Drive', address_2='')
    mcs_corp = Company(company_name='MCS Corporation', address='5151 S. Hannibal Way', address_2='')
    mbmi_metal_building = Company(company_name='MBMI Metal Buildings', address='955 NW 17th Ave., Building H', address_2='')
    metallic_building_comp = Company(company_name='Metallic Building Company', address='10043 Red Sage Drive', address_2='')
    midwest_steel_works = Company(company_name='Midwest Steel Works, Inc.', address='P.O. Box 81096', address_2='')
    murr_welding_design = Company(company_name='Murr Welding & Design', address='240 North 16th Street', address_2='')
    myers_comp_arch_metals = Company(company_name='Myer\'s & Company Architectural Metals', address='P.O. Box 2570', address_2='555 Basalt Ave.')
    nall_company = Company(company_name='Nall & Company, Inc.', address='424 Harriet Street', address_2='')
    pacific_coast_steel = Company(company_name='Pacific Coast Steel', address='166 East 14000 South, #120', address_2='')
    pioneer_steel = Company(company_name='Pioneer Steel, Inc.', address='51783 Hwy. 6', address_2='')
    pitkin_iron_corp = Company(company_name='Pitkin Iron Corp.', address='P.O. Box 1298', address_2='')
    portland_systems = Company(company_name='Portland Systems', address='4251 Kipling Street, #250', address_2='')
    pro_steel = Company(company_name='Pro Steel, Inc.', address='38805 Myers Road', address_2='')
    puma_steel = Company(company_name='Puma Steel', address='1720 Pacific Ave.', address_2='')
    r_m_steel_comp = Company(company_name='R & M Steel Company', address='P.O. Box 580', address_2='')
    redd_iron = Company(company_name='Redd Iron, Inc.', address='10421 E. 106th Ave.', address_2='')
    ricks_welding = Company(company_name='Rick\'s Welding', address='2124 Hwy. 6 & 50', address_2='')
    rigid_global_building = Company(company_name='Rigid Global Buildings', address='10 Inverness Drive East, Suite 220', address_2='')
    rocky_mountain_steel = Company(company_name='Rocky Mountain Steel, Inc.', address='P.O. Box 486', address_2='')
    rocky_mountain_steel_structures = Company(company_name='Rocky Mountain Steel Structures', address='353 East Vista Drive', address_2='')
    sanpete_steel = Company(company_name='Sanpete Steel, LLC', address='685 East Main', address_2='')
    s_s_welding_fabrication = Company(company_name='S & S Welding and Fabrication, Inc.', address='3138 F 1/2 Road', address_2='')
    schaenburg_flexadux = Company(company_name='Schaenburg Flexadux', address='2233 Sanford Drive', address_2='')
    stryan_structural_systems = Company(company_name='Stryan Structural Systems', address='200 S. Wilcox St.', address_2='PMB #306')
    sunward_consolidated_group = Company(company_name='Sunward Consolidated Group', address='6800 E. Hampden Ave.', address_2='')
    thunder_mountain_testing = Company(company_name='Thunder Mountain Testing', address='2970 N. Ronlin Ave.', address_2='')
    timberwolf_welding = Company(company_name='Timberwolf Welding, Inc.', address='3938 Highway 348', address_2='')
    todds_welding = Company(company_name='Todd\'s Welding, Inc.', address='1560 River Road', address_2='')
    tpi_industrial = Company(company_name='TPI Industrial, Inc.', address='', address_2='')
    united_metal_fabrication = Company(company_name='United Metal Fabrication Corp.', address='4224 North Nevada Ave., Suite 110', address_2='')
    varco_pruden_buildings = Company(company_name='Varco Pruden Buildings', address='27570 Silver Spur Street', address_2='')
    vulcraft_sales = Company(company_name='Vulcraft Sales', address='2140 S. Ivanhoe Street, Suite G9', address_2='')
    western_slope_iron = Company(company_name='Western Slope Iron & Supply, Inc.', address='670 23 Road', address_2='')
    wilkins_masonry_works = Company(company_name='Wilkins\' Masonry Works, Inc.', address='240 Elm Ave.', address_2='')
    zimkor = Company(company_name='Zimkor, LLC', address='P.O. Box 1006', address_2='')


    list_5 = [abc_supply, alliance_steel, all_metals_welding, all_steel, american_standard_steel, artec, b_c_steel_corp, behlen_building, bishop_welding_fabrication, blaze_constructors, braemar_building, butler_manufacturing, ceco_building_systems, chief_buildings, c_l_welding, cladding_component_sol, clemmer_welding, collins_metal_design, contact_welding_services, custom_structural_steel, division_iv, dmd_fab, dons_welding, doughty_steel_machine, duane_phipps, dw_metal_works, dynamic_metal_works, empire_steel_buildings, fast_e_nal, foundation_repair_western_co, freedom_steel_buildings, frontier_steel_building, garfield_steel_machine, greylen_steel_buildings, industrial_systems, insulated_panel_systems, iron_man_mize, iron_monkey_metal, keystone_custom_builders, kingspan, j_m_steel_sol, leachs_industrial_service, mach2_construction, mackey_metal_roofing, metal_building_services, mcs_corp, mbmi_metal_building, metallic_building_comp, midwest_steel_works, murr_welding_design, myers_comp_arch_metals, nall_company, pacific_coast_steel, pioneer_steel, pitkin_iron_corp, portland_systems, pro_steel, puma_steel, r_m_steel_comp, redd_iron, ricks_welding, rigid_global_building, rocky_mountain_steel, rocky_mountain_steel_structures, sanpete_steel, s_s_welding_fabrication, schaenburg_flexadux, stryan_structural_systems, sunward_consolidated_group, thunder_mountain_testing, timberwolf_welding, todds_welding, tpi_industrial, united_metal_fabrication, varco_pruden_buildings, vulcraft_sales, western_slope_iron, wilkins_masonry_works, zimkor]


    # WOOD & PLASTICS
    eighty_four_lumber = Company(company_name='84 Lumber Co.', address='779 - 22 Road', address_2='')
    ac_construction = Company(company_name='AC Construction', address='', address_2='')
    a_golden_touch = Company(company_name='A Golden Touch', address='2891 Texas Ave.', address_2='')
    alpine_chinking = Company(company_name='Alpine Chinking', address='13374 6650 Road', address_2='')
    alpine_lumber = Company(company_name='Alpine Lumber Co.', address='61408 Jay Jay Road', address_2='')
    ark_woodworks = Company(company_name='Ark Woodworks', address='878 Baseline Place, Unit A', address_2='')
    best_tops = Company(company_name='Best Tops', address='1250 North 3rd', address_2='')
    bettos_construction = Company(company_name='Bettos Construction', address='2837 North Ave. #F43', address_2='')
    boise_cascade = Company(company_name='Boise Cascade', address='', address_2='')
    break_of_dawn_construc = Company(company_name='Break of Dawn Construction, Inc.', address='9527 Cove Creek Drive', address_2='')
    cart_works_company = Company(company_name='Cart Works Company', address='1550 West Evans Ave., Unit Z', address_2='')
    cedar_creek_builders = Company(company_name='Cedar Creek Builders', address='P.O. Box 840869', address_2='')
    colbran_supply = Company(company_name='Colbran Supply', address='203 Main Street', address_2='')
    concepts_milwork = Company(company_name='Concepts in Millwork, Inc.', address='1490 Tuskegee Place', address_2='')
    construction_crew = Company(company_name='Construction Crew, LLC', address='', address_2='')
    cornerstone_construction = Company(company_name='Cornerstone Construction, LLC', address='441 Denver Ave.', address_2='')
    czzh_enterprises = Company(company_name='CZZH Enterprises, LLC', address='6881 S. Versailes Way, #102', address_2='')
    dallas_creek_construction = Company(company_name='Dallas Creek Construction', address='P.O. Box 1270', address_2='')
    danish_craftsmen = Company(company_name='Danish Craftsmen, Inc.', address='8730 West 14th Ave.', address_2='')
    d_z_construction = Company(company_name='D & Z Construction', address='637 Round Table Road', address_2='')
    dca_discount_cabinets = Company(company_name='DCA Discount Cabinets & Appliances', address='P.O. Box 8749', address_2='')
    delta_cabinet_comp = Company(company_name='Delta Cabinet Company', address='696 Industrial Blvd.', address_2='')
    donnie_suaza_construc = Company(company_name='Donnie Suaza Construction', address='P.O. Box 253', address_2='')
    dubworks = Company(company_name='Dubworks', address='205 N. Elizabeth', address_2='')
    fort_collins_truss = Company(company_name='Fort Collins Truss', address='201 NW Frontage Road', address_2='')
    frontier_log_homes = Company(company_name='Frontier Log Homes', address='60813 Maple Grove Road', address_2='')
    hadden_enterprises = Company(company_name='Hadden Enterprises, LLC', address='3002 W. Fox Park Road', address_2='')
    haldeman_homme = Company(company_name='Haldeman-Homme, Inc.', address='6200 South Syracuse Way, Suite 120', address_2='')
    hellers_interiors = Company(company_name='Heller\'s Interiors', address='1180 Valley Street', address_2='')
    j_k10_cabinetry = Company(company_name='J & K10 Cabinetry Ltd.', address='5151 Bannock Street #8', address_2='')
    ked_development = Company(company_name='KED Development / Kedrowski Builders', address='P.O. Box 532', address_2='')
    kinney_construction = Company(company_name='Kinney Construction', address='1776 K 6/10 Road', address_2='')
    kitchen_bath_designs = Company(company_name='Kitchen & Bath Designs', address='1601 Oxbow Drive, Unit 360B', address_2='')
    knights_construction = Company(company_name='Knights Construction', address='2312 Orchard Ave.', address_2='')
    m_m_countertops = Company(company_name='M & M Countertops', address='11943 County Rd #320', address_2='')
    marquez_constrution = Company(company_name='Marquez Construction, LLC', address='P.O. Box 3087', address_2='')
    millenium_west_builders = Company(company_name='Millenium West Builders', address='1667 Laveta Street', address_2='')
    osburn_cabinets_design = Company(company_name='Osburn Cabinets & Design', address='682 West Gunnison Ave.', address_2='')
    overholt_truss = Company(company_name='Overholt Truss Co.', address='1796 Hwy. 50', address_2='739 Rood Ave.')
    peak_1_stairs_woodworking = Company(company_name='Peak 1 Stairs & Woodworking, LLC', address='5243 South Rio Grande Street, Suite A', address_2='')
    prime_win_corp = Company(company_name='Prime Win Corporation', address='P.O. Box 365', address_2='')
    pro_build = Company(company_name='Pro-Build', address='2773 Riverside Parkway', address_2='16 W. Main')
    reeder_construction = Company(company_name='Reeder Construction, Inc.', address='945 E. 6th', address_2='')
    rpa_chinking = Company(company_name='RPA Chinking', address='1420 Haystack Road', address_2='')
    schnell_builders = Company(company_name='Schnell Builders', address='P.O. Box 442', address_2='')
    sma_framing = Company(company_name='SMA Framing', address='3228 Red Maple Court', address_2='')
    strength_construction = Company(company_name='Strength Construction', address='37090 Highway 550', address_2='')
    timberline_fasteners = Company(company_name='Timberline Fasteners', address='6195 Clermont Street', address_2='')
    tims_custom_countertops = Company(company_name='Tim\'s Custom Countertops & Cabinets', address='4040 - 5945 Road', address_2='')
    the_kitchen_center = Company(company_name='The Kitchen Center', address='1031 S. 15th Street', address_2='')
    tj_builders = Company(company_name='TJ Builders, LLC', address='2601 CR 233', address_2='')
    the_spacecreators = Company(company_name='The SpaceCreators', address='361 - 27 1/2 Road', address_2='')
    trumble_builders = Company(company_name='Trumble Builders', address='4200 Waterfall Drive', address_2='')
    truss_co = Company(company_name='Truss Co.', address='23360 S. Hwy. 550', address_2='')
    valley_lumber_co = Company(company_name='Valley Lumber Co.', address='2495 Railroad Ave.', address_2='')
    van_dyk_construction = Company(company_name='Van Dyk Construction, Inc.', address='12905 Division Street, Unit A', address_2='')
    western_cabinets = Company(company_name='Western Cabinets', address='2065 East Main', address_2='')
    woodworkers_of_gj = Company(company_name='Woodworkers of Grand Junction, Inc.', address='2906 I-70 Business Loop', address_2='')



    list_6 = [eighty_four_lumber, ac_construction, a_golden_touch, alpine_chinking, alpine_lumber, ark_woodworks, best_tops, bettos_construction, boise_cascade, break_of_dawn_construc, cart_works_company, cedar_creek_builders, colbran_supply, concepts_milwork, construction_crew, cornerstone_construction, czzh_enterprises, dallas_creek_construction, danish_craftsmen, d_z_construction, dca_discount_cabinets, delta_cabinet_comp, donnie_suaza_construc, dubworks, fort_collins_truss, frontier_log_homes, hadden_enterprises, haldeman_homme, hellers_interiors, j_k10_cabinetry, ked_development, kinney_construction, kitchen_bath_designs, knights_construction, m_m_countertops, marquez_constrution, millenium_west_builders, osburn_cabinets_design, overholt_truss, peak_1_stairs_woodworking, prime_win_corp, pro_build, reeder_construction, rpa_chinking, schnell_builders, sma_framing, strength_construction, timberline_fasteners, tims_custom_countertops, the_kitchen_center, tj_builders, the_spacecreators, trumble_builders, truss_co, valley_lumber_co, van_dyk_construction, western_cabinets, woodworkers_of_gj]


    # THERMAL & MOISTURE PROTECTION
    aaa_waterproofing = Company(company_name='AAA Waterproofing, Inc.', address='1779 Airport Road', address_2='')
    accurate_insulation = Company(company_name='Accurate Insulation, Inc.', address='685 W. Gunnison #106', address_2='113 Rose Lane, Unit F')
    adobe_creek_environmental = Company(company_name='Adobe Creek Environmental Services', address='1987 N. Road', address_2='')
    allied_building_products = Company(company_name='Allied Building Products', address='2495 West Mesa Court', address_2='')
    allied_insulation = Company(company_name='Allied Insulation', address='6395 Brighton Blvd.', address_2='')
    alpine_mechanical_insul = Company(company_name='Alpine Mechanical Insulators, Inc.', address='331 S. 13th Street', address_2='')
    american_roof_co = Company(company_name='American Roof Co.', address='656 Larkspur Lane', address_2='')
    bauen = Company(company_name='Bauen', address='801 E. 52nd Ave.', address_2='')
    bay_insulation = Company(company_name='Bay Insulation Co.', address='3700 Havana Street, Unit 312', address_2='')
    black_canyon_roofing = Company(company_name='Black Canyon Roofing', address='P.O. Box 335', address_2='')
    central_states_roofing = Company(company_name='Central States Roofing', address='5925 Omaha Blvd.', address_2='')
    co_roofing_waterproofing = Company(company_name='Colorado Roofing & Waterproofing', address='2474 I Road', address_2='')
    co_west_damproofing = Company(company_name='Colorado West Damproofing', address='2654 Sacoma Court', address_2='')
    d7_roofing = Company(company_name='D-7 Roofing, LLC', address='1001 S. Galapago Street', address_2='')
    d_d_roofing = Company(company_name='D & D Roofing', address='6270 East 50th Ave.', address_2='')
    douglass_colony = Company(company_name='Douglass Colony', address='191 Soccer Field Road', address_2='')
    emc_roofing = Company(company_name='EMC Roofing', address='1513 M 1/8 Road', address_2='')
    faith_construction = Company(company_name='Faith Construction (DO NOT USE)', address='504 - 28 1/2 Road', address_2='')
    front_range_roofing = Company(company_name='Front Range Roofing Systems, LLC', address='222 13th Ave.', address_2='')
    gzo_sheet_metal_roofing = Company(company_name='GZO Sheet Metal & Roofing', address='P.O. Box 1475', address_2='')
    hurst_roofing_construction = Company(company_name='Hurst Roofing & Construction Co.', address='703 Nugget Drive', address_2='')
    innovative_roofing_sol = Company(company_name='Innovative Roofing Solutions', address='', address_2='')
    j_d_seamless_gutters = Company(company_name='J & D Seamless Gutters, LLC', address='', address_2='')
    jblanco_enterprises = Company(company_name='JBlanco Enterprises', address='1 Park Street', address_2='')
    kc_roofing_construction = Company(company_name='KC Roofing & Construction, LLC', address='2810 1/2 Bookcliff Ave.', address_2='')
    kruger_roofing = Company(company_name='Kruger Roofing, LLC', address='914 South Ave.', address_2='')
    line_x_gj = Company(company_name='Line-X of Grand Junction', address='549 Bogart Lane', address_2='')
    mato = Company(company_name='MATO', address='4850 Lima Street', address_2='')
    mgm_waterproofing_restoration = Company(company_name='M.G.M. Waterproofing & Restoration, Inc.', address='800 E. 64th Ave., Unit 1', address_2='')
    millennium_waterproofing = Company(company_name='Millennium Waterproofing, Inc.', address='P.O. Box 1499', address_2='')
    odyssey_construction = Company(company_name='Odyssey Construction, Inc.', address='520 Hwy. 92', address_2='')
    outwest_drywall = Company(company_name='Outwest Drywall', address='2148 Highway 6 & 50', address_2='')
    pacific_sheet_metal = Company(company_name='Pacific Sheet Metal', address='P.O. Box 70', address_2='0794 Industry...?')
    pint_roofing_construction = Company(company_name='Pint Roofing & Construction (OUT OF BUSINESS)', address='573 S. Commercial Drive, Suite 2', address_2='')
    pioneer_materials_west_slope = Company(company_name='Pioneer Materials West Slope', address='3156 Perkins Drive', address_2='P.O. Box 280')
    ppp_roofing = Company(company_name='PPP Roofing, Inc.', address='2648 McCormick Ave.', address_2='')
    purgatory_contracting = Company(company_name='Purgatory Contracting', address='P.O. Box 1294', address_2='')
    red_eagle_construction = Company(company_name='Red Eagle Construction', address='P.O. Box 398', address_2='')
    reliant_roofing = Company(company_name='Reliant Roofing, Inc.', address='554 25 Road, Suite 5', address_2='')
    rocky_mountain_companies = Company(company_name='Rocky Mountain Companies, LLC', address='2944 I-70 Business Loop, #210', address_2='')
    roof_check = Company(company_name='Roof Check', address='1610 Skyway Drive', address_2='')
    roofing_plus = Company(company_name='Roofing Plus', address='10766 6330 Road', address_2='')
    roofing_supply_group = Company(company_name='Roofing Supply Group', address='11919 E. 37th Ave.', address_2='')
    rycenga_construction = Company(company_name='Rycenga Construction, LLC', address='11623 Joyful Way', address_2='')
    seamless_gutters = Company(company_name='Seamless Gutters by Juan', address='4360 Blue Sage Drive', address_2='')
    sgh_inc = Company(company_name='SGH, Inc.', address='56 Inverness Drive East, Suite 102', address_2='')
    shingleworks_roofing = Company(company_name='Shingleworks Roofing, Inc.', address='2193 Avenal Lane', address_2='')
    stealth_roofing = Company(company_name='Stealth Roofing Co.', address='3456 F Road', address_2='')
    summit_sealants_restoration = Company(company_name='Summit Sealants & Restoration, Inc.', address='13671 Carefree Drive', address_2='')
    summit_systems_consulting = Company(company_name='Summit Systems Consulting', address='2535 Hall Ave.', address_2='')
    superior_roofing = Company(company_name='Superior Roofing, Inc.', address='14700 East 39th Ave.', address_2='')
    team_panels_internat = Company(company_name='TEAM Panels International', address='3700 Windermere Street', address_2='')
    tecta_america = Company(company_name='Tecta America', address='1881 W. 13th Ave.', address_2='')
    telluride_roofing = Company(company_name='Telluride Roofing, Inc.', address='P.O. Box 2276', address_2='')
    tl_roofing = Company(company_name='TL Roofing', address='825 E. 32nd Street', address_2='')


    list_7 = [aaa_waterproofing, accurate_insulation, adobe_creek_environmental, allied_building_products, allied_insulation, alpine_mechanical_insul, american_roof_co, bauen, bay_insulation, black_canyon_roofing, central_states_roofing, co_roofing_waterproofing, co_west_damproofing, d7_roofing, d_d_roofing, douglass_colony, emc_roofing, faith_construction, front_range_roofing, gzo_sheet_metal_roofing, hurst_roofing_construction, innovative_roofing_sol, j_d_seamless_gutters, jblanco_enterprises, kc_roofing_construction, kruger_roofing, line_x_gj, mato, mgm_waterproofing_restoration, millennium_waterproofing, odyssey_construction, outwest_drywall, pacific_sheet_metal, pint_roofing_construction, pioneer_materials_west_slope, ppp_roofing, purgatory_contracting, red_eagle_construction, reliant_roofing, rocky_mountain_companies, roofing_plus, roof_check, roofing_supply_group, rycenga_construction, seamless_gutters, sgh_inc, shingleworks_roofing, stealth_roofing, summit_sealants_restoration, summit_systems_consulting, superior_roofing, team_panels_internat, tecta_america, telluride_roofing, tl_roofing]


    # DOORS & WINDOWS
    a_i_a = Company(company_name='A.I.A. (Applied Industrial & Architectural)', address='290 East 56th Ave.', address_2='')
    alpine_custom_doors = Company(company_name='Alpine Custom Doors & Millwork, Inc.', address='P.O. Box 3923', address_2='2842 Chipeta...?')
    alpine_glass = Company(company_name='Alpine Glass', address='573 West Crete Circle, #201', address_2='')
    ambassador_blind_shutter = Company(company_name='Ambassador Blind N Shutter, Inc.', address='658 Faircloud Way', address_2='')
    anderson_windows_doors = Company(company_name='Anderson Windows & Doors', address='', address_2='')
    b_b_glass_window = Company(company_name='B & B Glass & Window', address='693 Industrial Blvd.', address_2='')
    black_canyon_window_design = Company(company_name='Black Canyon Window Designs', address='2480 N. Townsend Ave.', address_2='')
    bratton_window_door = Company(company_name='Bratton Window & Door, Inc.', address='1921 I-70 Business Loop', address_2='')
    budget_blinds = Company(company_name='Budget Blinds (DO NOT USE)', address='2494 W. Mesa Court', address_2='')
    champion_enterprises = Company(company_name='Champion Enterprises, Inc.', address='2037 W. 14th Ave.', address_2='')
    chucks_glass = Company(company_name='Chuck\'s Glass', address='129 W. Main Street', address_2='')
    co_doorways = Company(company_name='Colorado Doorways', address='5151 Bannock Street, #17', address_2='')
    co_precast_concrete = Company(company_name='Colorado Precast Concrete', address='1820 E. Hwy. 402', address_2='')
    custom_expressions = Company(company_name='Custom Expressions', address='1130 Elm Street', address_2='')
    denver_hardware_comp = Company(company_name='Denver Hardware Company', address='3200 Walnut Street', address_2='')
    devcon_group = Company(company_name='Devcon Group, Inc. (DO NOT USE)', address='2379 Haystack Road', address_2='')
    dh_pace_door_service = Company(company_name='DH Pace Door Services', address='4200 Monaco Street', address_2='')
    e_e_door_window = Company(company_name='E & E Door & Window', address='2898 I-70 Business Loop', address_2='')
    elmer_glass_comp = Company(company_name='Elmer Glass Company', address='2117 Whiteriver Ave.', address_2='P.O. Box 1209')
    encore_window_converings = Company(company_name='Encore Window Converings, Inc.', address='3316 Tejon Street', address_2='')
    glass_brokerage = Company(company_name='Glass Brokerage, Inc.', address='118 N. 22nd Court', address_2='')
    glass_pros = Company(company_name='Glass Pros', address='2486 Commerce Blvd.', address_2='')
    glass_doctor = Company(company_name='Glass Doctor', address='2480 N. Townsend Ave.', address_2='')
    golesh_door = Company(company_name='Golesh Door', address='2345 S. Delaware Street', address_2='')
    high_class_glass_skylight = Company(company_name='High Class Glass & Skylights, Inc.', address='1485 Kingston Street', address_2='')
    jb_window_special = Company(company_name='JB Window Specialties', address='P.O. Box 271', address_2='')
    lannie_rund = Company(company_name='Lannie & Rund, Inc.', address='640 Independent Ave.', address_2='')
    lucas_drapery_install = Company(company_name='Lucas Drapery Installation', address='132 E. Alcove Drive', address_2='')
    lu_tek = Company(company_name='Lu-Tek, Inc.', address='5135 W. 58th Ave., Unit #5', address_2='')
    mckinney_door_hardware = Company(company_name='McKinney Door & Hardware', address='2700 N. Freeway', address_2='')
    metro_glass = Company(company_name='Metropolitan Glass, Inc.', address='6400 Franklin Street', address_2='')
    mike_harmeling_construction = Company(company_name='Mike Harmeling Construction Services', address='103 N. Easter Hill Drive', address_2='')
    montrose_glass = Company(company_name='Montrose Glass, Inc.', address='3998 - 5500 Road', address_2='')
    mountain_country_windows_doors = Company(company_name='Mountain Country Windows & Doors', address='2898 I-70 Business Loop', address_2='')
    mountain_view_window_door = Company(company_name='Mountain View Window & Door', address='2511 N. 12th Street', address_2='')


    list_8 = [a_i_a, alpine_custom_doors, alpine_glass, ambassador_blind_shutter, anderson_windows_doors, b_b_glass_window, black_canyon_window_design, bratton_window_door, budget_blinds, champion_enterprises, chucks_glass, co_doorways, co_precast_concrete, custom_expressions, denver_hardware_comp, devcon_group, dh_pace_door_service, e_e_door_window, elmer_glass_comp, encore_window_converings, glass_brokerage, glass_pros, glass_doctor, golesh_door, high_class_glass_skylight, jb_window_special, lannie_rund, lucas_drapery_install, lu_tek, mckinney_door_hardware, metro_glass, mike_harmeling_construction, montrose_glass, mountain_country_windows_doors, mountain_view_window_door]


    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_companie():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.companies RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM companies"))

    db.session.commit()
